/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RocCheckboxToggle {
    'check': () => Promise<void>;
    'checked': boolean;
    'color': 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'dark' | 'light';
    'disabled': boolean;
    'size': 'sm' | 'md' | 'lg';
    'toggle': () => Promise<void>;
    'uncheck': () => Promise<void>;
  }
}

declare namespace LocalJSX {
  interface RocCheckboxToggle extends JSXBase.HTMLAttributes {
    'checked'?: boolean;
    'color'?: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'dark' | 'light';
    'disabled'?: boolean;
    'onChange'?: (event: CustomEvent<any>) => void;
    'size'?: 'sm' | 'md' | 'lg';
  }

  interface IntrinsicElements {
    'roc-checkbox-toggle': RocCheckboxToggle;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLRocCheckboxToggleElement extends Components.RocCheckboxToggle, HTMLStencilElement {}
  var HTMLRocCheckboxToggleElement: {
    prototype: HTMLRocCheckboxToggleElement;
    new (): HTMLRocCheckboxToggleElement;
  };

  interface HTMLElementTagNameMap {
    'roc-checkbox-toggle': HTMLRocCheckboxToggleElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

